[package]
name = "tme"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tme"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }

anyhow = "1.0.87"
chrono = "0.4.38"

[dev-dependencies]
pretty_assertions = "1.4.0"
rstest = "0.22.0"
